<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Visual feedback_demo-frame</name>
   <tag></tag>
   <elementGuidId>56f7d61c-c8a3-4c94-a6ba-740b16818996</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.demo-frame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>69b0e5d2-d4da-493c-8212-96e6c45e8f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/resources/demos/droppable/default.html</value>
      <webElementGuid>08b18eb4-0084-4180-b68e-96cf7d4b4a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>demo-frame</value>
      <webElementGuid>9dca5c4c-affe-4cea-9fff-2424b83da1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/iframe[@class=&quot;demo-frame&quot;]</value>
      <webElementGuid>db375353-9608-4ffe-bae0-dfbec80e34e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/iframe</value>
      <webElementGuid>6474edf9-d216-46bb-b414-c9b369039ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>00e48702-d1c0-41e9-a440-26b6784c2bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/resources/demos/droppable/default.html']</value>
      <webElementGuid>9f35cd39-ef83-4d21-a43a-de902006446f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
